version: '3.3'

services:
  printrider:
    image: "sketch-rider:0.1"
    depends_on:
      - dynamo
    volumes:
      - ~/.aws:/root/.aws
    environment:
      APP_DYNAMO: http://localhost:8000
      MICRONAUT_ENVIRONMENTS: dev
    ports:
      - 8080:8080
    links:
      - dynamo:dynamo
  dynamo:
    image: "instructure/dynamo-local-admin"
    ports:
      - 8000:8000
volumes:
  db_data: