micronaut:
  application:
    name: sketchrider

# oauth
---
micronaut:
  security:
    enabled: true
    intercept-url-map:
      -
        pattern: /static/**
        http-method: GET
        access:
          - isAnonymous()
    oauth2:
      enabled: true
      clients:
        github:
          client-id: "${GITHUB_CLIENT_ID}"
          client-secret: "${GITHUB_CLIENT_SECRET}"
          scopes:
            - read:user
          authorization:
            url: 'https://github.com/login/oauth/authorize'
          token:
            url: 'https://github.com/login/oauth/access_token'
            auth-method: client-secret-post
    endpoints:
      logout:
        enabled: true
        get-allowed: true
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_SIG_GENERATOR}"

# client
---
micronaut:
  http:
    services:
      githubv3:
        url: "https://api.github.com"

# static resources
---
micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"